name: MSBuild C++

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
        
jobs:
    build:
        runs-on: windows-latest
        
        steps:
        
            - name: Checkout
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Setup NuGet
              uses: NuGet/setup-nuget@fd55a6f3b34392fa83fde1454582407d8c714123 # v4
              
            - name: Restore NuGet Packages
              run: nuget restore "Arena Allocator.sln"
  
            - name: Configure MSBuild
              uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3
              
            - name: Compile project (Release & x64)
              run: msbuild "Arena Allocator.sln" /p:Configuration=Release /p:Platform=x64
            
            - name: Run Unit Tests
              run: .\x64\Release\ArenaTests.exe
            
            